vim.g.mapleader = ' '
vim.keymap.set('n', '<leader>r', function()
  vim.cmd('!mise run run')
end)
vim.keymap.set('n', '<leader>b', function()
  vim.cmd('!mise build')
end)
vim.keymap.set('n', '<leader>n', function()
  vim.cmd('e .')
end)
