vim.g.mapleader = ' '
vim.keymap.set('n', '<leader>r', function()
  vim.cmd('terminal mise run run')
  vim.cmd('startinsert')
end)
vim.keymap.set('n', '<leader>b', function()
  vim.cmd('!mise build')
end)
vim.keymap.set('n', '<leader>t', function()
  vim.cmd('!mise test')
end)
vim.keymap.set('n', '<leader>n', function()
  vim.cmd('e .')
end)
vim.keymap.set('n', '<leader>ev', function()
  vim.cmd('ConjureEvalFile')
end)
